# This file is a template, and might need editing before it works on your project.

.build_script: &build_script
  - export HTTP_PROXY=$CI_PROXY HTTPS_PROXY=$CI_PROXY NO_PROXY=nexus3.nexus3,new-page.xyz
  - make all

stages:
  - build
  - deploy

dev-1.11:
  tags:
    - sourcemod
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - *build_script
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*

merge-check:
  tags:
    - sourcemod
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - git config --global user.email "runner@gitlab.com"
    - git config --global user.name "Runner"
    - git pull origin master
    - *build_script
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy:
  tags:
    - ftp
  stage: deploy
  script:
    - lftp -c "set sftp:connect-program 'ssh -o StrictHostKeyChecking=no';set sftp:auto-confirm yes;open -u $SOURCEMOD_SFTP_USER,$SOURCEMOD_SFTP_PASS sftp://$SOURCEMOD_SFTP_HOST;mirror -Rv compiled plugins --ignore-time --transfer-all --parallel=50 --exclude-glob .git* --exclude .git/;bye"
  only:
    - master
  needs:
    - job: dev-1.11
      artifacts: true
