# This file is a template, and might need editing before it works on your project.
image: registry.new-page.xyz/newpage/sourcemod-builder:latest

.build_script: &build_script
  - make all

build-dev-1.11:
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - *build_script
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*

build-1.10:
  stage: build
  script:
    - *build_script
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*

merge-check:
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git checkout master
    - git merge $CI_COMMIT_REF_NAME
    - *build_script
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
