# This file is a template, and might need editing before it works on your project.
image: registry.new-page.xyz/newpage/sourcemod-builder:latest

.build_script: &build_script
  - make all

stages:
  - build
  - deploy

dev-1.11:
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - *build_script

merge-check:
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - git config --global user.email "runner@gitlab.com"
    - git config --global user.name "Runner"
    - git pull origin master
    - *build_script
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy:
  image: alpine
  stage: deploy
  script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk add --no-cache --update lftp openssh
    - lftp -c "set sftp:auto-confirm yes;open -u $SOURCEMOD_SFTP_USER,$SOURCEMOD_SFTP_PASS sftp://$SOURCEMOD_SFTP_HOST;mirror -Rv compiled plugins --ignore-time --transfer-all --parallel=50 --exclude-glob .git* --exclude .git/;bye"
  only:
    - master
  needs:
    - job: dev-1.11
      artifacts: true
