# This file is a template, and might need editing before it works on your project.
image: registry.new-page.xyz/newpage/sourcemod-builder:latest

.build_script: &build_script
  - make all

dev-1.11:
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - *build_script

csgo-build-1.10:
  stage: build
  variables:
    API_URL: $API_URL_CSGO
  script:
    - *build_script
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*

ins-build-1.10:
  stage: build
  variables:
    API_URL: $API_URL_INS
  script:
    - *build_script
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*

merge-check:
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - git config --global user.email "runner@gitlab.com"
    - git config --global user.name "Runner"
    - git pull origin master
    - *build_script
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
