# This file is a template, and might need editing before it works on your project.
image: registry.new-page.xyz/newpage/sourcemod-builder:latest

before_script:
  - make env

build-dev-1.11:
  stage: build
  variables:
    SOURCEMOD_VERSION: "1.11"
  script:
    - make build
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*

build-1.10:
  stage: build
  script:
    - make build
  artifacts:
    expire_in: 1 week
    paths:
      - compiled/*
